# using default gitpod mysql workspace
image:
  file: .gitpod.Dockerfile

# # exposing 3000 JIC
# ports:
#   - port: 3000
#     onOpen: open-preview

# load in workshop specific data on workspace init
tasks:
  - init: mysql -u root < data/sakila-schema.sql && mysql -u root < data/sakila-data.sql && clear && mysql -u root
